name: Update CONTRIBUTORS
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: minicli/action-contributors@v1.1
        name: 'Update a projects CONTRIBUTORS file'
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CONTRIB_REPOSITORY: 'jbrooksuk/artisan.page'
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
